### ISSUE TITLE
Missing dependency: Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by daraber** [MyIntelligenceAgency/semantic-fleet#24]
**Describe the bug**
Latest NuGet release of **MyIA.SemanticKernel.Connectors.AI.Oobabooga** is broken.

`System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

**To Reproduce**
1. Create a new solution & install _**MyIA.SemanticKernel.Connectors.AI.Oobabooga**_ NuGet package
2. `Kernel.Builder.WithOobaboogaChatCompletionService(new OobaboogaChatCompletionSettings(), string.Empty).Build();`
3. Run solution

**Platform**
 - OS: Windows
 - IDE: Jetbrains Rider 2023.2.2
 - Language: C#
 - Source: MyIA.SemanticKernel.Connectors.AI.Oobabooga 0.33.9

**Additional context**
AFAIK Microsoft.Bcl is deprecated. Explicitly install **Microsoft.Bcl.AsyncInterfaces** to fix this issue.

**Comment by jsboige** [comment]
@daraber I updated the lib to support the latest SK version. I also added a Console app referencing the latest Nuget package to make sure those errors are gone now.
