### ISSUE TITLE
Broken NuGet release: OobaboogaChatCompletion

### ISSUE THREAD

**Issue by daraber** [MyIntelligenceAgency/semantic-fleet#25]
**Describe the bug**
Latest NuGet release of **MyIA.SemanticKernel.Connectors.AI.Oobabooga** is broken.

`Unhandled exception. System.TypeLoadException: Method 'GetChatCompletionsAsync' in type 'MyIA.SemanticKernel.Connectors.AI.Oobabooga.Completion.ChatCompletion.OobaboogaChatCompletion' from assembly 'MyIA.SemanticKernel.Connectors.AI.Oobabooga, Version=0.33.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at MyIA.SemanticKernel.Connectors.AI.Oobabooga.OobaboogaKernelBuilderExtensions.WithOobaboogaChatCompletionService(KernelBuilder builder, OobaboogaChatCompletionSettings settings, String serviceId, Boolean alsoAsTextCompletion, Boolean setAsDefault)
   at Program.<Main>$(String[] args) in Program.cs:line 22
`

**To Reproduce**
1. Create a new solution & install **MyIA.SemanticKernel.Connectors.AI.Oobabooga** NuGet package
2. `Kernel.Builder.WithOobaboogaChatCompletionService(new OobaboogaChatCompletionSettings(), string.Empty).Build();`
3. Run solution

**Platform**
 - OS: Windows
 - IDE: Jetbrains Rider 2023.2.2
 - Language: C#
 - Source: MyIA.SemanticKernel.Connectors.AI.Oobabooga 0.33.9

**Comment by jsboige** [comment]
@daraber Can you test the latest Nuget package? It shouldn't have that issue now
