### ISSUE TITLE
Missing class: CompleteRequestSettings

### ISSUE THREAD

**Issue by daraber** [MyIntelligenceAgency/semantic-fleet#26]
**Describe the bug**
Class `CompleteRequestSettings` is not included in NuGet release, thus the quick start example is broken.

**To Reproduce**
1. Replicate quick start
2. See error

**Platform**
 - OS: Windows
 - IDE: Jetbrains Rider 2023.2.2
 - Language: C#
 - Source: MyIA.SemanticKernel.Connectors.AI.Oobabooga 0.33.9

**Additional context**
I find it strange that there were deprecation annotations committed to the official Semantic Kernel Oobabooga connector in favor of this when there are multiple fatal issues in the NuGet release making it totally unusable.

**Comment by jsboige** [comment]
Latest Nuget package should have fixed pending issues
